### ISSUE TITLE
Traj 0 unmatched as point 364 and 365 not connected

### ISSUE THREAD

**Issue by snowman109** [cyang-kth/fmm#126]
When i run the match_wkt method, a waring appears. 
```
[2020-10-22 21:36:29.860] [warning] [fmm_algorithm.cpp:291] Traj 0 unmatched as point 364 and 365 not connected
```
My gps points is really not connected, this is the points figure.
![image](https://user-images.githubusercontent.com/26241639/96898875-d08c5200-14c2-11eb-8890-d34b78725da6.png)

I try to solve it by grouping these points  by distance, for example, if the distance between the xth point and the (x+1)th point is more than 500m, i will set these points to the different grroups and then match each group. But it doesn't work.

I want to know how to judge whether to connect or not.  Could you give me some advice to solve it?

**Comment by cyang-kth** [comment]
@snowman109 
This warning means that each candidate edge found for your point 364 cannot be connected to any candidate edge found for your point 365. 

It could happen in two cases:
- Two points are too distant from each other, which exceeds the upperbound of UBODT so that their candidate edges are also distant from each other and no distance is found from UBODT. I think it is your case, and if you split the large gap into separate trajectories you should be able to fix it.
- The network contains topology errors, namely, two parts of the network are not connected (perhaps some important links are missing or has the wrong direction information).

I think you need to first split the trajectory by large gap, then match each one individually. If it cannot be matched, you need to check which two points are disconnected. In some complex network circumstances like overpass, you may need to set a large k value to include more candidates.
