### ISSUE TITLE
Error in Docker build

### ISSUE THREAD

**Issue by meshalawy** [cyang-kth/fmm#134]
Hi, I am building the docker image. I cloned the repo and executed the docker build command provided in the docker directory. However, I am getting this error as shown in the screenshot. 

Output of:
`docker build -f docker/Dockerfile . -t fmm:0.1.0`

![image](https://user-images.githubusercontent.com/3316260/97809618-02e63e00-1c7f-11eb-95a5-c82e0fcf646f.png)

I am running Mac OSX

Any ideas what is wrong here?

**Comment by cyang-kth** [comment]
Thank you for pointing out this error. 

I encounter the same problem and it seems to be the object file placed in the target_link_libraries. 

I have corrected this problem is the latest commit https://github.com/cyang-kth/fmm/commit/dc9518c3cf53e05f09c8c21f0203932da02335ef

Please pull the latest version and the error should disappear.

**Comment by meshalawy** [comment]
Thanks for the quick response. I pulled the latest update and it builds without any issues. 

Thanks again.
