### ISSUE TITLE
Dockerfile is not working

### ISSUE THREAD

**Issue by Kwafoor** [cyang-kth/fmm#146]
**Describe the bug**
when i run docker to have a image,i have this bug.

c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/NETWORK.dir/src/network/network.cpp.o] Error 4
CMakeFiles/NETWORK.dir/build.make:110: recipe for target 'CMakeFiles/NETWORK.dir/src/network/network.cpp.o' failed
CMakeFiles/Makefile2:400: recipe for target 'CMakeFiles/NETWORK.dir/all' failed
Makefile:127: recipe for target 'all' failed
make[1]: *** [CMakeFiles/NETWORK.dir/all] Error 2
make: *** [all] Error 2
The command '/bin/sh -c mkdir -p build &&     cd build &&     cmake .. &&     make install' returned a non-zero code: 2

**Comment by cyang-kth** [comment]
Which platform or environment are you running? The problem seems to be related with memory limit of your docker. 

https://stackoverflow.com/questions/30887143/make-j-8-g-internal-compiler-error-killed-program-cc1plus
https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container/44533437#44533437

**Comment by Kwafoor** [comment]
Oh,yes,you are right!Thank you very much.I success,when growing the limit of my vm.
