### ISSUE TITLE
Wrong map matching using stmatch

### ISSUE THREAD

**Issue by ziXet** [cyang-kth/fmm#189]
Hi,

I've been working with this library for a while and found it really elegant!

Today, I faced this issue in map matching using stmatch. I already changed the input parameters to get the correct map matching result but was not successful.

Issue:
stmatch is giving a wrong map matching result.

stmatch command:
`
stmatch --network ./edges.shp -k 8 -r 0.003 --vmax 0.005 --gps 1.csv --network_id id --source u --target v --output 1.out.csv --use_omp
`
* unit is degree

**Expected behavior**
stmatch should calculate the matching path correctly.

**Screenshots**
Input Trajectory:
![Screenshot from 2021-04-09 16-58-45](https://user-images.githubusercontent.com/1327949/114240041-e4cee900-9954-11eb-8b07-0d3152f7715f.png)

Output:

mgeom:
![Screenshot from 2021-04-09 16-57-07](https://user-images.githubusercontent.com/1327949/114240068-eef0e780-9954-11eb-85b2-0f5bae5d18ef.png)

pgeom:
![Screenshot from 2021-04-09 16-56-41](https://user-images.githubusercontent.com/1327949/114240083-f617f580-9954-11eb-8c51-a5dece367c76.png)

Network:
![Screenshot from 2021-04-09 16-23-22](https://user-images.githubusercontent.com/1327949/114237635-5efd6e80-9951-11eb-9376-170876b0651c.png)

Zip file including network shape file and input/output.
[test.zip](https://github.com/cyang-kth/fmm/files/6288470/test.zip)

Any help would be appreciated.

Thanks!

**Comment by cyang-kth** [comment]
@ziXet 

The reason is that at road intersections, there are a lot of candidate edges so k=8 is too small to cover the correct candidate. After setting k=16, it seems to be correct now.

```bash
stmatch --network ./edges.shp -k 16 -r 0.003 --vmax 0.005 --gps 1.csv \
--network_id id --source u --target v --output 2.out.csv
```

#### k = 8

![a](https://user-images.githubusercontent.com/6810084/114256519-5a39c880-99ec-11eb-82cf-f076a30738c8.png)

#### k = 16

![b](https://user-images.githubusercontent.com/6810084/114256533-789fc400-99ec-11eb-8d00-bcaa4aafc13e.png)
