### ISSUE TITLE
delta int only?

### ISSUE THREAD

**Issue by tias** [cyang-kth/fmm#20]
Hi,

Thanks for the quick response earlier.

It seems that, even though the README suggests to use a 'delta' of 0.01, that supplying a floating-point delta is not read by the ubodt config. Instead, if you enter something like 0.01 or 3.1 then it falls back to the default of '5000' (which is gigantic in case of degrees...)

https://github.com/cyang-kth/fmm/blob/c36af04c8d24b3541b6ee6729036b4d147097d2f/app/config.hpp#L220

Thanks,
Tias

**Comment by cyang-kth** [comment]
Thank you for pointing out the problem. The reason is that get function will parse the string content based on the default argument 5000, which is in integer type. Consequently, when float value is specified, the parse will fail and default value is returned as 5000.  

I have updated the default value of delta to be float, which should fix the problem. 

https://github.com/cyang-kth/fmm/blob/5fc1ae71e45e0756d41789001ae7e82f4c407f3a/app/config.hpp#L220
