### ISSUE TITLE
failed to import _fmm

### ISSUE THREAD

**Issue by miaomiaomao** [cyang-kth/fmm#41]
Sorry to disturb you again.
I met some problem while installing the python extension:
My environment is 
     Ubuntu 16.04
     swig 4.0.0
     Python 2.7
When I run  `python fmm_test.py` ,I met the following problem:

Traceback (most recent call last):
  File "../fmm/web_demo/fmm_web_app.py", line 14, in <module>
    from fmm import MapMatcher
  File "/home/project/test_map/fmm/python/build/fmm.py", line 17, in <module>
    _fmm = swig_import_helper()
  File "/home/project/test_map/fmm/python/build/fmm.py", line 16, in swig_import_helper
    return importlib.import_module('_fmm')
  File "/home/anaconda3/envs/python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dynamic module does not define init function (init_fmm)

I've build _fmm.so and add the build folder to the environment variable.

I've installed the C++ extension. In fact, I just want to get the link id (cpath). It seems that I got id of dual road netwok by following the step in osm_mapmatching. Should I use edge.shp as input directly if I want each segment of road appear only once ?
Now I have 7000 trips , shall I make them into one trip.shp file (Because I want the same road segment in each trip have the same id)? Besides, I saved these data in csv file and list data structure in python, do you have some suggesstions on changing the data into 'trip.shp' and 'trip.shx'?

Thank you very much!

**Comment by cyang-kth** [comment]
@miaomiaomao 

1. Your problem with importing python might be that you have multiple Python installed. The python used to build the library is different from the default Python. You need to check the
output of `make` to see which python lib is used. 

2. The link id is the id of the road edge in the dual network. You cannot use the original network as input because its topology is incomplete. To infer the original ID. You need to have some kinds of postprocessing. 

3. The trips should be placed in one shp file containing 7000 features. To change the data from CSV to SHP, you can use [geopandas](http://geopandas.org/) or use QGIS software to add delimited text layer and export as SHP. For the latter case, the geometry of your trips should be saved as WKT format, like this 

```
id;geom
1;LINESTRING (30 10, 10 30, 40 40)
```

**Comment by miaomiaomao** [comment]
I checked the CmakeCache.txt and found the version of python consist with my default python.
I found that in the example.png, the road network is not always pairwise. It seems that the number of the segments'id is irregular. Do you have some suggestion on post-processing? 
I'll try to change my data to SHP. Thank you for your suggestion.

**Comment by cyang-kth** [comment]
@miaomiaomao 
The edges.shp in the example folder assumes that the network is complete so that each edge is one-way direction and there is no need to add the reverse one. However, in reality, it is common that you have an edge that is bidirectional (the geometry of that edge is still one direction). In that case, the edge on the reverse direction should be added. 

For the postprocessing I think you need to export also the original network ID and then in Python read all the IDs into a dictionary and you can iterate through the cpath to export their original ID.

**Comment by miaomiaomao** [comment]
I've done the postprocessing. Thank you for your suggestion.
