### ISSUE TITLE
How do I get the source/target id in the Shapefile via the candidates dataframe

### ISSUE THREAD

**Issue by davmol** [cyang-kth/fmm#65]
Hi, first of all thank you for this amazing, easy to use package. After a successful map matching via the python API, I would like to receive the original source and target id from the input geometry network (shapefile) for each matched point. I hat thought it would correlate to the target source from the candidates dataframe, but it doesn't, right? Is there a way I can retrieve the source target id from the original input geometry network (shapefile) - not the source target id from the hash table - for each matched point?

candidates dataframe with first matched point looks like this:
```
;index;edge_id;source;target;dist;length;offset;ep
0;0;3993735;3740467;3740468;20.35569649663184;51.693102473857465;40.11285553629971;0.9204699943397221
```

Furthermore im curious why I don't get a result.txt  after the map matching (using Version 31.01.2020)

in fmm_config.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<fmm_config>
  <input>
    <ubodt>
      <file>data/ubodt_deu_100_32632_6.bin</file>
    </ubodt>
    <network>
      <file>data/network_deu_32632_6.shp</file>
      <id>id</id>
      <source>source</source>
      <target>target</target>
    </network>
  </input>
  <parameters>
    <k>8</k> <!-- -->
    <r>300</r><!-- 0.0005 4326-->
    <!--<pf>0</pf><! -->
    <gps_error>50</gps_error> <!--0.0001 4326 -->
  </parameters>
  <output>
    <fields>
      <all/>
      <!-- <ogeom/> <error/> <opath/> <cpath/> -->
    </fields>
    <file>results.txt</file>
  </output>
  <other>
    <log_level>0</log_level>
  </other>
</fmm_config>
```

**Comment by cyang-kth** [comment]
@davmol 
I think the version you are using is too old where substantial changes have been made to the library. 
However, in the latest version I have removed functions written for Python API in this file. 

https://github.com/cyang-kth/fmm/blob/536c24f5bf78ecc19d6809405439ba93b427e4f2/python/fmm.h

In the latest version of the Python API, however, you will be able to actually read a network in Python directly. 
https://github.com/cyang-kth/fmm/blob/master/example/notebook/fmm_example.ipynb
The two values should be the same in the latest version. The source/target field in the network shapefile and the one exported in the data frame. 

The latest version supports only exporting the matched candidate for each point. 

Python API is not designed for exporting an output file because the input data depends on the user's input. If you are use Python API, you need to export the information by writing your own python code. The fmm configuration file you provided misses an argument for input GPS data.

In the latest version of the API, you specify every input argument yourself as shown here
https://github.com/cyang-kth/fmm/blob/master/example/notebook/fmm_example.ipynb

If you want to generate an output file automatically, you need to actually use the command line (C++ program).

**Comment by davmol** [comment]
Thank you very much for the quick response! I already figured that there were made some changes to the API according to the new notebook file. Ok, so updating to the latest version should solve my main issue, as I understand. Hence the output of the candidates (now only the matched point) should give me the  source and target ids as well as the `result.opath` should give me the edges of the network shape? Why has was there a different handling for the candidates source targets and the ones in the network shape?

**Comment by cyang-kth** [comment]
@davmol 

You should have the expected result. A documentation is available at
https://fmm-wiki.github.io/docs/documentation/output/

The old version you were using actually returns the source and target NodeIndex (which is from 0 to number of vertices -1) rather than NodeID which is the one stored in Shapefile. The node index is used in graph creation and routing. The node ID is actually used as output.

**Comment by davmol** [comment]
@cyang-kth 
perfect! thank you for you help! I'will clone the current version and give it another try.
