### ISSUE TITLE
Windows platform support

### ISSUE THREAD

**Issue by cyang-kth** [cyang-kth/fmm#87]
Deploy the framework to windows platform, preferably directly build with Visual Studio and use appveyor for continuous integration test.

**Comment by cyang-kth** [comment]
[vcpkg](https://github.com/microsoft/vcpkg) may be a nice tool to manage the dependency.

**Comment by cyang-kth** [comment]
It seems that the vcpkg is extremely slow in downloading and installing specific libraries.

**Comment by zhangwei0402** [comment]
The windows deployment problem can be simply solved by adding the absolute path to fmm/build folder to PATH environment variable, i.e.,

echo 'export PATH=${PATH}:PATH_TO_BUILD_FOLDER' >> ~/.bashrc
source ~/.bashrc

or, copying cygpyfmmlib.dll from fmm/build folder to fmm/build/python folder.

The reason was that _fmm.dll could not find this dependency.

**Comment by cyang-kth** [comment]
This issue has been addressed in https://github.com/cyang-kth/fmm/commit/ce207a5bf003f77a6474386463c97c0f6c23ba72 and windows platform is tested on Appveyor.
